### ISSUE TITLE
requirements-dev.txt does not refer to requirements.txt

### ISSUE THREAD

**Issue by denizgenc** [alphagov/cyber-security-security-advisory-dashboard#190]
Hi guys, I ran `test.sh` to check with some Dependabot PRs, and I got errors telling me that I was missing `requests` and `addict`. I figured out that this was because these packages were only referenced in `requirements.txt`, and `requirements-dev.txt` does not reference it.

Adding a
```
-r requirements.txt
```
 to the top of the file would be appreciated - or an explanation for the separation between these two files.

Thanks!

**Comment by alice-carr** [comment]
Hey Deniz
This  relates to what we were talking about here but I'll document it for anyone that reads.

Previously, we had no instruction in our README on how to run tests - they're set up to run with our Makefile which runs our tests using a docker container that installs both requirements.txt and requirements-dev.txt. Running the tests locally with test.sh would indeed not work - we've now added how to run tests into the readme to make it clearer how to run tests.

I'll close this issue now
